export enum REACT_QUERY_KEYS {
  GET_FEEDBACKS = "GET_FEEDBACKS",
  GET_FEEDBACKS_DONE = "GET_FEEDBACKS_DONE",
  GET_STAFF_EMAILS = "GET_STAFF_EMAILS",
  GET_MY_FEEDBACKS = "GET_MY_FEEDBACKS",
  POST_CAREER_REQUEST = "POST_CAREER_REQUEST"
}
